apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 992382454035.dkr.ecr.ap-south-1.amazonaws.com/react:<tag>  
        ports:
        - containerPort: 80  
        
