name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       docker build -t react:latest .
    - name: Log in docker
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: push docker image
      run: |
          docker image tag react:latest rohan7300/react:latest
          docker push rohan7300/react:latest
          
    - name: Configure-aws-credentials
      uses: aws-actions/Configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ap-south-1
        
    - name: login to ecr
    - id: login ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: build, Tag
      id: build-image
      env:
        ECR_REGISTORY: ${{  steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lesson-086
        IMAGE_TAG: latest
      run: |
         docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
         docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
