name: CI
on:
 push:
  branches:
   -main
jobs:
 build:
  runs-on: ubuntu:latest

  steps:
   - name: Checkout code
     uses: action/checkout@v3

   - name: Build Docker Image
     run: |
      docker run -t react:latest .
